version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - 'POSTGRES_D8=nest'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=84051408oi'
    ports:
      - '5432:5432'

  service1:
    build:
      context: ./bank
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/ms-bank
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 84051408oi

  service2:
    build:
      context: ./comment
    ports:
      - "8088:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/ms-comment
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 84051408oi

  service3:
    build:
      context: ./company
    ports:
      - "8086:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/ms-company
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 84051408oi

  service4:
    build:
      context: ./email
    ports:
      - "8085:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/ms-email
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 84051408oi

  service5:
    build:
      context: ./friendship
    ports:
      - "8089:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/ms-friendship
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 84051408oi

  service6:
    build:
      context: ./game
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/ms-game
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 84051408oi

  service7:
    build:
      context: ./invoice
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/ms-invoice
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 84051408oi

  service8:
    build:
      context: ./likesdislikes
    ports:
      - "8092:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/ms-likesdiskiles
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 84051408oi

  service9:
    build:
      context: ./order
    ports:
      - "8087:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/ms-order
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 84051408oi

  service10:
    build:
      context: ./player
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/ms-player
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 84051408oi

  service11:
    build:
      context: ./user
    ports:
      - "8084:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/ms-user
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 84051408oi
