apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
      labels:
        app: bank
    spec:
      containers:
        - name: bank
          image: lcooser/bank:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://localhost:5432/ms-bank
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: 84051408oi
---
apiVersion: v1
kind: Service
metadata:
  name: bank
spec:
  selector:
    app: bank
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type : LoadBalancer