name: Build, Push, and Deploy to Kubernetes

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construir e enviar imagens
      - name: Build and push Docker images
        run: |
          for service in bank comment email friendship game invoice likesdislikes order player user; do
            echo "Building and pushing $service"
            docker build -t ${{ secrets.DOCKER_USERNAME }}/$service:latest ./microservices_pb/steam-microservices/$service
            docker push ${{ secrets.DOCKER_USERNAME }}/$service:latest
          done

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Set kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f microservices_pb/steam-microservices/k8s/

      - name: Get logs
        run: |
          for service in bank comment email friendship game invoice likesdislikes order player user; do
            echo "Logs for $service:"
            kubectl logs -l app=$service --tail=100
          done
